services:
  app:
    image: maldet-pipeline:latest
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials
      - ./config.yaml:/config.yaml
      - ./schema.yaml:/schema.yaml
      - ./params.yaml:/params.yaml

    environment:
      - SERVER_URI=<Enter mongodb server uri>
